import type { Experience } from "@/lib/types";

export const experience: Experience[] = [
  {
    company: "Skil-Dev",
    role: "Web Full Stack Developer",
    location: "Cairo, Egypt",
    period: "Aug 2024 - Present",
    start: "2024-08",
    current: true,
    summary:
      "Full-stack feature work on microservices that carry finance data between enterprise platforms.",
    stack: [
      "TypeScript",
      "NestJS",
      "Node.js",
      "MongoDB",
      "PostgreSQL",
      "TypeORM",
      "RabbitMQ",
      "Redis",
      "React",
      "Next.js",
      "Grafana",
      "Jest",
    ],
    metrics: [
      { label: "platforms integrated", value: "D365 + Odoo" },
      { label: "service messaging", value: "Event-driven" },
    ],
    highlights: [
      "Designed and developed full-stack features across backend and frontend, delivering end-to-end functionality for production systems.",
      "Contributed to the design and implementation of scalable microservices-based backend systems using TypeScript, NestJS, Node.js, MongoDB and PostgreSQL, improving maintainability and performance.",
      "Designed and implemented integrations between Microsoft Dynamics 365 Finance, Odoo and custom third-party financial systems, enabling seamless data synchronization and improving financial workflows.",
      "Implemented event-driven communication patterns using RabbitMQ, improving system decoupling and enabling reliable asynchronous processing across services.",
      "Used Redis for caching and performance optimization, reducing response times and improving efficiency under high load.",
      "Managed database schema evolution and migrations with TypeORM, ensuring data consistency and smooth deployments.",
      "Improved observability by integrating monitoring and visualization tools such as Grafana, enabling faster issue diagnosis.",
      "Built dynamic, reusable frontend components, forms and business logic with React and Next.js, and increased test coverage with Jest.",
    ],
  },
  {
    company: "Block Gemini",
    role: "Full Stack Software Engineer",
    location: "Dubai, UAE",
    period: "Jan 2024 - Aug 2024",
    start: "2024-01",
    end: "2024-08",
    summary:
      "Led geo-search optimization over a 10M-record dataset and built the logging pipeline the team monitored it with.",
    stack: [
      "NestJS",
      "TypeORM",
      "PostgreSQL",
      "GraphQL",
      "Redis",
      "Elasticsearch",
      "Kibana",
      "Filebeat",
      "JWT",
      "Swagger",
      "Next.js 14",
      "Tailwind CSS",
    ],
    metrics: [
      { label: "records searched", value: "10M+" },
      { label: "geo-query p95, target under 1s", value: "600ms" },
    ],
    highlights: [
      "Led the optimization of geo-location search queries over large datasets using Elasticsearch, achieving an average query response of 600ms against a target under 1s while processing 10 million records.",
      "Designed RESTful APIs with NestJS, TypeORM and PostgreSQL, improving performance of complex data-retrieval operations.",
      "Used GraphQL to streamline data querying and improve client-side performance, with Redis as a caching layer.",
      "Integrated JWT authentication and role-based authorization across microservices, enhancing security while keeping the system scalable.",
      "Built and maintained a logging system with Filebeat, Kibana and Elasticsearch for real-time log collection, monitoring and visualization, working with DevOps to integrate it into backend systems.",
      "Documented APIs with Swagger, improving developer experience and reducing integration time.",
      "Contributed to frontend work with Next.js 14 and Tailwind CSS, integrating NestJS APIs with React and Next.js frontends.",
      "Collaborated with a multi-national team across Dubai, India, Romania and Egypt in a fast-paced environment.",
    ],
  },
];
