import type { Experience } from "@/lib/types";

export const experience: Experience[] = [
  {
    company: "Skil-Dev",
    role: "Web Full Stack Developer",
    location: "Cairo, Egypt",
    period: "Aug 2024 - Present",
    start: "2024-08",
    current: true,
    summary:
      "Backend services for a production multi-tenant SaaS platform, where domain services communicate asynchronously over RabbitMQ message patterns behind a single API gateway.",
    stack: [
      "TypeScript",
      "NestJS",
      "Node.js",
      "PostgreSQL",
      "MongoDB",
      "TypeORM",
      "RabbitMQ",
      "Redis",
      "React",
      "Next.js",
      "OpenTelemetry",
      "Grafana",
      "Docker",
      "GitHub Actions",
      "Jest",
    ],
    metrics: [
      { label: "services and frontends", value: "~40" },
      { label: "service messaging", value: "Event-driven" },
      { label: "platforms integrated", value: "D365 + Odoo" },
    ],
    highlights: [
      "Built backend services for a production multi-tenant SaaS platform spanning roughly 40 service and frontend applications, across logistics and financial-operations domains.",
      "Contributed to domain microservices in TypeScript and NestJS — service boundaries, message contracts, tenant isolation, and event-driven communication over RabbitMQ with idempotent consumers.",
      "Designed integrations between Microsoft Dynamics 365 Finance, Odoo and custom third-party financial systems, synchronizing documents and postings through asynchronous, message-based flows.",
      "Worked across PostgreSQL, MongoDB and Redis, with OpenTelemetry tracing and Grafana dashboards, to keep production systems reliable and observable under load.",
      "Built features across independently deployed Next.js applications composed behind a shared shell, shipped as Docker images through GitHub Actions CI.",
    ],
  },
  {
    company: "Block Gemini",
    role: "Full Stack Software Engineer",
    location: "Dubai, UAE",
    period: "Jan 2024 - Aug 2024",
    start: "2024-01",
    end: "2024-08",
    summary:
      "Led geo-search optimization over a 10M-record dataset and built the logging pipeline the team monitored it with.",
    stack: [
      "NestJS",
      "TypeORM",
      "PostgreSQL",
      "GraphQL",
      "Redis",
      "Elasticsearch",
      "Kibana",
      "Filebeat",
      "JWT",
      "Swagger",
      "Next.js 14",
      "Tailwind CSS",
    ],
    metrics: [
      { label: "records searched", value: "10M+" },
      { label: "geo-query p95, target under 1s", value: "600ms" },
    ],
    highlights: [
      "Led the optimization of geo-location search over a 10-million-record dataset using Elasticsearch, achieving a 600 ms average query response time against a sub-1-second target.",
      "Designed RESTful APIs with NestJS, TypeORM and PostgreSQL, improving performance of complex data-retrieval operations, and used GraphQL with a Redis caching layer to streamline client-side querying.",
      "Implemented JWT authentication and role-based authorization across microservices, keeping access control consistent between services without sacrificing scalability.",
      "Built and maintained a centralized logging pipeline with Filebeat, Elasticsearch and Kibana for real-time log collection, monitoring and visualization, working with DevOps to integrate it into backend services.",
      "Contributed frontend features with Next.js 14 and Tailwind CSS and integrated them with the NestJS APIs, collaborating with a multi-national team across Dubai, India, Romania and Egypt.",
    ],
  },
];
