import type { Experience } from "@/lib/types";

export const experience: Experience[] = [
  {
    company: "Skil-Dev",
    role: "Web Full Stack Developer",
    location: "Cairo, Egypt",
    period: "Aug 2024 - Present",
    start: "2024-08",
    current: true,
    summary:
      "Backend services for a production multi-tenant SaaS platform, where domain services communicate over RabbitMQ message patterns behind a single API gateway rather than direct HTTP calls.",
    stack: [
      "TypeScript",
      "NestJS",
      "Node.js",
      "PostgreSQL",
      "MongoDB",
      "TypeORM",
      "RabbitMQ",
      "Redis",
      "React",
      "Next.js",
      "OpenTelemetry",
      "Grafana",
      "Docker",
      "GitHub Actions",
      "Jest",
    ],
    metrics: [
      { label: "services and frontends", value: "~40" },
      { label: "service messaging", value: "Event-driven" },
      { label: "platforms integrated", value: "D365 + Odoo" },
    ],
    highlights: [
      "Build backend services for a multi-tenant SaaS platform spanning roughly 40 service and frontend applications, across logistics and financial-operations domains.",
      "Contributed to the design and implementation of domain microservices in TypeScript, NestJS and Node.js, taking part in service decomposition, message contracts and inter-service communication patterns.",
      "Implemented event-driven asynchronous communication with RabbitMQ, using idempotent consumers so redelivered or retried messages cannot apply the same operation twice.",
      "Built tenant-scoped services in a multi-tenant architecture where per-tenant data isolation is enforced at the data-access layer and authorization is resolved centrally at the gateway against role-based policies.",
      "Designed and built integrations between Microsoft Dynamics 365 Finance, Odoo and custom third-party financial systems, synchronizing financial documents and postings through asynchronous, message-based flows.",
      "Modelled and evolved relational and document schemas across PostgreSQL and MongoDB, managing migrations with TypeORM to keep data consistent across independently deployed services.",
      "Used Redis caching and query optimization on read-heavy paths to reduce response times under load, and instrumented services with OpenTelemetry tracing and Grafana dashboards to shorten diagnosis of production issues.",
      "Built features in independently deployed Next.js micro-frontends composed behind a shared shell, shipped services as Docker images through GitHub Actions CI, and increased Jest coverage on backend logic.",
    ],
  },
  {
    company: "Block Gemini",
    role: "Full Stack Software Engineer",
    location: "Dubai, UAE",
    period: "Jan 2024 - Aug 2024",
    start: "2024-01",
    end: "2024-08",
    summary:
      "Led geo-search optimization over a 10M-record dataset and built the logging pipeline the team monitored it with.",
    stack: [
      "NestJS",
      "TypeORM",
      "PostgreSQL",
      "GraphQL",
      "Redis",
      "Elasticsearch",
      "Kibana",
      "Filebeat",
      "JWT",
      "Swagger",
      "Next.js 14",
      "Tailwind CSS",
    ],
    metrics: [
      { label: "records searched", value: "10M+" },
      { label: "geo-query p95, target under 1s", value: "600ms" },
    ],
    highlights: [
      "Led the optimization of geo-location search over large datasets with Elasticsearch, reaching 600ms average query response against a sub-1-second target while processing 10 million records.",
      "Designed RESTful APIs with NestJS, TypeORM and PostgreSQL, improving performance of complex data-retrieval operations, and used GraphQL with a Redis caching layer to streamline client-side querying.",
      "Implemented JWT authentication and role-based authorization across microservices, keeping access control consistent between services without sacrificing scalability.",
      "Built and maintained a centralized logging pipeline with Filebeat, Elasticsearch and Kibana for real-time log collection, monitoring and visualization, working with DevOps to integrate it into backend services.",
      "Documented APIs with Swagger, improving developer experience and reducing integration time for consuming teams.",
      "Contributed frontend features with Next.js 14 and Tailwind CSS and integrated them with the NestJS APIs, collaborating with a multi-national team across Dubai, India, Romania and Egypt.",
    ],
  },
];
